Feature/billing worklogs
aakb/jira_economics pull request #32
Opened 2019-08-27 13:19 UTC by tuj

* Changed from working with issues to registering worklogs to invoice entries.

2019-08-27 13:59 UTC, rimi-itk requested changes
Looks good. However, a few comments should be addressed.

2019-08-27 13:59 UTC, rimi-itk commented on src/Service/AbstractJiraService.php
> +        $worklogs = $this->post('rest/tempo-timesheets/4/worklogs/search', [
What is `4` here? An API version?

2019-08-27 13:59 UTC, rimi-itk commented on bundles/Billing/Resources/assets/css/react-datepicker.css
> +.react-datepicker-wrapper {
Maybe use `scss` and nesting?

2019-08-28 06:34 UTC, tuj commented on src/Service/AbstractJiraService.php
> +        $worklogs = $this->post('rest/tempo-timesheets/4/worklogs/search', [
Yes.

2019-08-28 07:08 UTC, rimi-itk approved these changes
Hooray!

2019-08-28 07:08 UTC, merged