JE-231: Minor improvements
aakb/jira_economics pull request #88
Opened 2020-01-24 11:35 UTC by rimi-itk

https://jira.itkdev.dk/browse/JE-231

2020-01-24 15:15 UTC, tuj requested changes

2020-01-24 15:15 UTC, tuj commented on src/Command/Migrate/MigrateUsersCommand.php
> +            if (null === $user) {
if ($isNew) {

2020-01-25 07:40 UTC, rimi-itk commented on src/Command/Migrate/MigrateUsersCommand.php
> +            if (null === $user) {
I've refactored this.

2020-01-26 11:01 UTC, tuj approved these changes

2020-01-27 08:22 UTC, merged